name: flutter_monitor_sdk
description: "A Flutter Monitor SDK for monitoring errors, performance, user behavior and UI jank."
version: 1.0.0
homepage: https://github.com/xinqingaa/flutter_monitor_sdk
repository: https://github.com/xinqingaa/flutter_monitor_sdk

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  dio: ^5.4.3+1
  device_info_plus: ^11.2.0
  package_info_plus: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 
